parameters:
    security.encoders:
        Symfony\Component\Security\Core\User\User : plaintext
    security.role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    security.providers.chain_provider.chain.providers: [in_memory]
    security.in_memory.memory.users:
        master:
            password: omega
            roles: 'ROLE_ADMIN'
    security.firewalls:
        lemlabs:
            anonymous: ~
            form_login:
                check_path: /admin-authentification/check
                login_path: /admin-authentification/login
                default_target_path: /
            logout:
                path: /admin-authentification/logout
                target: /admin-authentification/login
    security.access_control:
        - { path: ^/admin-authentification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        