parameters:
#    app_common.example.class: LemLabs\CommonBundle\Example

services:
#    app_common.example:
#        class: %app_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     app.twig.tools_extension:
        class: LemLabs\CommonBundle\Twig\ToolsExtension
        arguments:
            serviceContainer : "@service_container"
        tags:
            - { name: twig.extension }
            
     #Confirm service        
     confirm:
        class: LemLabs\CommonBundle\Services\Confirm\Confirm   
        arguments:
            - @twig
